[2023-05-30 22:05:41,342] root INFO ########################################################################
[2023-05-30 22:05:41,342] root INFO #                                                                      #
[2023-05-30 22:05:41,342] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-05-30 22:05:41,342] root INFO #                                                                      #
[2023-05-30 22:05:41,342] root INFO ########################################################################
[2023-05-30 22:05:41,342] pyhamilton.interface INFO starting a Hamilton interface
[2023-05-30 22:05:41,343] pyhamilton.interface INFO started the oem application for simulation
[2023-05-30 22:05:41,344] pyhamilton.interface INFO started the server thread
[2023-05-30 22:05:41,345] root INFO initialize: synchronously initialize the robot
[2023-05-30 22:05:59,367] root INFO Initializing TEC 0
[2023-05-30 22:06:00,368] pyhamilton.interface INFO sending end run command to simulator
[2023-05-30 22:06:01,869] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-05-30 22:06:01,869] pyhamilton.interface INFO disconnected from server
[2023-05-30 22:06:01,970] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-05-30 22:06:01,970] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-05-30 22:06:01,979] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-05-30 22:06:01,980] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-05-30 22:06:01,980] pyhamilton.interface INFO dummy get request sent to server
[2023-05-30 22:06:01,980] pyhamilton.interface INFO server thread exited
[2023-05-30 22:06:01,982] root ERROR Traceback (most recent call last):
[2023-05-30 22:06:01,982] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 34, in <module>
[2023-05-30 22:06:01,982] root ERROR initialize_tec(ham_int, 0)
[2023-05-30 22:06:01,983] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 13, in initialize_tec
[2023-05-30 22:06:01,983] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-05-30 22:06:01,983] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-05-30 22:06:01,983] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,984] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,985] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,987] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,988] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,989] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,990] root ERROR ^
[2023-05-30 22:06:01,991] root ERROR ^
[2023-05-30 22:06:01,991] root ERROR ^
[2023-05-30 22:06:01,991] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-05-30 22:06:01,991] root ERROR hamiltonResponse.raise_first_exception()
[2023-05-30 22:06:01,991] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-05-30 22:06:01,992] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-05-30 22:06:01,992] root ERROR pyhamilton.oemerr
[2023-05-30 22:06:01,993] root ERROR .
[2023-05-30 22:06:01,993] root ERROR HamiltonStepError
[2023-05-30 22:06:01,993] root ERROR : 
[2023-05-30 22:06:01,993] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_Initialize","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1ad006309730"} )
[2023-06-01 15:41:02,648] root INFO ########################################################################
[2023-06-01 15:41:02,649] root INFO #                                                                      #
[2023-06-01 15:41:02,649] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 15:41:02,650] root INFO #                                                                      #
[2023-06-01 15:41:02,650] root INFO ########################################################################
[2023-06-01 15:41:02,651] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 15:41:02,652] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 15:41:02,652] pyhamilton.interface INFO started the server thread
[2023-06-01 15:41:02,652] root INFO initialize: synchronously initialize the robot
[2023-06-01 15:42:16,687] root INFO Initializing TEC 0
[2023-06-01 15:42:21,690] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 15:42:23,191] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 15:42:23,191] pyhamilton.interface INFO disconnected from server
[2023-06-01 15:42:23,292] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 15:42:23,292] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 15:42:23,303] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 15:42:23,304] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 15:42:23,304] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 15:42:23,305] pyhamilton.interface INFO server thread exited
[2023-06-01 15:42:23,306] root ERROR Traceback (most recent call last):
[2023-06-01 15:42:23,306] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 21, in <module>
[2023-06-01 15:42:23,307] root ERROR initialize_tec(ham_int, 0)
[2023-06-01 15:42:23,307] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 13, in initialize_tec
[2023-06-01 15:42:23,307] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 15:42:23,308] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 15:42:23,314] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,315] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,316] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR ^
[2023-06-01 15:42:23,317] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 15:42:23,317] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 15:42:23,318] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 15:42:23,318] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 15:42:23,319] root ERROR pyhamilton.oemerr
[2023-06-01 15:42:23,319] root ERROR .
[2023-06-01 15:42:23,319] root ERROR HamiltonStepError
[2023-06-01 15:42:23,319] root ERROR : 
[2023-06-01 15:42:23,319] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_Initialize","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af2e59d1fdb"} )
[2023-06-01 15:49:11,539] root INFO ########################################################################
[2023-06-01 15:49:11,539] root INFO #                                                                      #
[2023-06-01 15:49:11,539] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 15:49:11,540] root INFO #                                                                      #
[2023-06-01 15:49:11,540] root INFO ########################################################################
[2023-06-01 15:49:11,540] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 15:49:11,540] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 15:49:11,540] pyhamilton.interface INFO started the server thread
[2023-06-01 15:49:11,540] root INFO initialize: synchronously initialize the robot
[2023-06-01 15:49:31,976] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 15:49:32,188] pyhamilton.interface INFO disconnected from server
[2023-06-01 15:49:32,289] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 15:49:32,289] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 15:49:32,293] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 15:49:32,294] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 15:49:32,294] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 15:49:32,294] pyhamilton.interface INFO server thread exited
[2023-06-01 15:49:32,294] root ERROR Traceback (most recent call last):
[2023-06-01 15:49:32,294] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 20, in <module>
[2023-06-01 15:49:32,296] root ERROR initialize(ham_int)
[2023-06-01 15:49:32,296] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\liquid_handling_wrappers.py", line 48, in initialize
[2023-06-01 15:49:32,296] root ERROR ham.wait_on_response(cmd, raise_first_exception=True, timeout=300)
[2023-06-01 15:49:32,297] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 646, in wait_on_response
[2023-06-01 15:49:32,297] root ERROR for _ in wait(delays=delays, timeout=timeout):
[2023-06-01 15:49:32,297] root ERROR   File "C:\Users\stefa\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\waiter\__init__.py", line 106, in __iter__
[2023-06-01 15:49:32,311] root ERROR time.sleep(min(delay, remaining))
[2023-06-01 15:49:32,311] root ERROR KeyboardInterrupt
[2023-06-01 15:49:32,311] root ERROR During handling of the above exception, another exception occurred:
[2023-06-01 15:49:32,311] root ERROR Traceback (most recent call last):
[2023-06-01 15:49:32,311] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 18, in <module>
[2023-06-01 15:49:32,312] root ERROR with HamiltonInterface(simulate=True) as ham_int:
[2023-06-01 15:49:32,312] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 571, in __exit__
[2023-06-01 15:49:32,312] root ERROR self.stop()
[2023-06-01 15:49:32,313] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 535, in stop
[2023-06-01 15:49:32,313] root ERROR self.wait_on_response(self.send_command(command='end', id=hex(0)), timeout=1.5)
[2023-06-01 15:49:32,313] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 646, in wait_on_response
[2023-06-01 15:49:32,314] root ERROR for _ in wait(delays=delays, timeout=timeout):
[2023-06-01 15:49:32,314] root ERROR   File "C:\Users\stefa\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\waiter\__init__.py", line 106, in __iter__
[2023-06-01 15:49:32,314] root ERROR time.sleep(min(delay, remaining))
[2023-06-01 15:49:32,315] root ERROR KeyboardInterrupt
[2023-06-01 15:49:33,367] root INFO ########################################################################
[2023-06-01 15:49:33,368] root INFO #                                                                      #
[2023-06-01 15:49:33,368] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 15:49:33,368] root INFO #                                                                      #
[2023-06-01 15:49:33,368] root INFO ########################################################################
[2023-06-01 15:49:33,368] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 15:49:33,368] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 15:49:33,368] pyhamilton.interface INFO started the server thread
[2023-06-01 15:49:33,368] root INFO initialize: synchronously initialize the robot
[2023-06-01 15:49:42,375] root INFO Initializing TEC 0
[2023-06-01 15:49:43,375] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 15:49:44,876] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 15:49:44,876] pyhamilton.interface INFO disconnected from server
[2023-06-01 15:49:44,977] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 15:49:44,977] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 15:49:44,980] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 15:49:44,981] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 15:49:44,981] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 15:49:44,981] pyhamilton.interface INFO server thread exited
[2023-06-01 15:49:44,982] root ERROR Traceback (most recent call last):
[2023-06-01 15:49:44,982] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 21, in <module>
[2023-06-01 15:49:44,982] root ERROR initialize_tec(ham_int, 0, True)
[2023-06-01 15:49:44,983] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 13, in initialize_tec
[2023-06-01 15:49:44,983] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 15:49:44,983] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 15:49:44,983] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,984] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,985] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,986] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR ^
[2023-06-01 15:49:44,987] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 15:49:44,987] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 15:49:44,988] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 15:49:44,988] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 15:49:44,988] root ERROR pyhamilton.oemerr
[2023-06-01 15:49:44,989] root ERROR .
[2023-06-01 15:49:44,989] root ERROR HamiltonStepError
[2023-06-01 15:49:44,989] root ERROR : 
[2023-06-01 15:49:44,989] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_Initialize","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af3002dc6ab"} )
[2023-06-01 15:59:14,567] root INFO ########################################################################
[2023-06-01 15:59:14,567] root INFO #                                                                      #
[2023-06-01 15:59:14,567] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 15:59:14,567] root INFO #                                                                      #
[2023-06-01 15:59:14,567] root INFO ########################################################################
[2023-06-01 15:59:14,569] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 15:59:14,569] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 15:59:14,569] pyhamilton.interface INFO started the server thread
[2023-06-01 15:59:14,569] root INFO initialize: synchronously initialize the robot
[2023-06-01 15:59:24,573] root INFO Initializing TEC 0
[2023-06-01 15:59:25,574] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 15:59:27,075] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 15:59:27,075] pyhamilton.interface INFO disconnected from server
[2023-06-01 15:59:27,175] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 15:59:27,176] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 15:59:27,180] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 15:59:27,180] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 15:59:27,181] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 15:59:27,181] pyhamilton.interface INFO server thread exited
[2023-06-01 15:59:27,181] root ERROR Traceback (most recent call last):
[2023-06-01 15:59:27,181] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 21, in <module>
[2023-06-01 15:59:27,181] root ERROR initialize_tec(ham_int, 0, True)
[2023-06-01 15:59:27,181] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 13, in initialize_tec
[2023-06-01 15:59:27,181] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 15:59:27,182] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 15:59:27,182] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,182] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,184] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR ^
[2023-06-01 15:59:27,185] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 15:59:27,186] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 15:59:27,186] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 15:59:27,186] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 15:59:27,186] root ERROR pyhamilton.oemerr
[2023-06-01 15:59:27,186] root ERROR .
[2023-06-01 15:59:27,186] root ERROR HamiltonStepError
[2023-06-01 15:59:27,186] root ERROR : 
[2023-06-01 15:59:27,186] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_Initialize","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af322e16d1f"} )
[2023-06-01 16:09:41,243] root INFO ########################################################################
[2023-06-01 16:09:41,243] root INFO #                                                                      #
[2023-06-01 16:09:41,243] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 16:09:41,243] root INFO #                                                                      #
[2023-06-01 16:09:41,244] root INFO ########################################################################
[2023-06-01 16:09:41,244] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 16:09:41,244] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 16:09:41,244] pyhamilton.interface INFO started the server thread
[2023-06-01 16:09:41,244] root INFO initialize: synchronously initialize the robot
[2023-06-01 16:09:49,603] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 16:09:49,787] pyhamilton.interface INFO disconnected from server
[2023-06-01 16:09:49,888] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 16:09:49,888] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 16:09:49,894] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 16:09:49,895] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 16:09:49,895] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 16:09:49,895] pyhamilton.interface INFO server thread exited
[2023-06-01 16:09:49,895] root ERROR Traceback (most recent call last):
[2023-06-01 16:09:49,895] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 20, in <module>
[2023-06-01 16:09:49,896] root ERROR initialize(ham_int)
[2023-06-01 16:09:49,896] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\liquid_handling_wrappers.py", line 48, in initialize
[2023-06-01 16:09:49,896] root ERROR ham.wait_on_response(cmd, raise_first_exception=True, timeout=300)
[2023-06-01 16:09:49,896] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 646, in wait_on_response
[2023-06-01 16:09:49,897] root ERROR for _ in wait(delays=delays, timeout=timeout):
[2023-06-01 16:09:49,897] root ERROR   File "C:\Users\stefa\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\waiter\__init__.py", line 106, in __iter__
[2023-06-01 16:09:49,897] root ERROR time.sleep(min(delay, remaining))
[2023-06-01 16:09:49,897] root ERROR KeyboardInterrupt
[2023-06-01 16:09:49,897] root ERROR During handling of the above exception, another exception occurred:
[2023-06-01 16:09:49,897] root ERROR Traceback (most recent call last):
[2023-06-01 16:09:49,897] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 18, in <module>
[2023-06-01 16:09:49,897] root ERROR with HamiltonInterface(simulate=True) as ham_int:
[2023-06-01 16:09:49,899] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 571, in __exit__
[2023-06-01 16:09:49,899] root ERROR self.stop()
[2023-06-01 16:09:49,899] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 535, in stop
[2023-06-01 16:09:49,899] root ERROR self.wait_on_response(self.send_command(command='end', id=hex(0)), timeout=1.5)
[2023-06-01 16:09:49,899] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 646, in wait_on_response
[2023-06-01 16:09:49,899] root ERROR for _ in wait(delays=delays, timeout=timeout):
[2023-06-01 16:09:49,899] root ERROR   File "C:\Users\stefa\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\waiter\__init__.py", line 106, in __iter__
[2023-06-01 16:09:49,900] root ERROR time.sleep(min(delay, remaining))
[2023-06-01 16:09:49,900] root ERROR KeyboardInterrupt
[2023-06-01 16:09:50,932] root INFO ########################################################################
[2023-06-01 16:09:50,932] root INFO #                                                                      #
[2023-06-01 16:09:50,932] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 16:09:50,932] root INFO #                                                                      #
[2023-06-01 16:09:50,932] root INFO ########################################################################
[2023-06-01 16:09:50,932] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 16:09:50,933] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 16:09:50,933] pyhamilton.interface INFO started the server thread
[2023-06-01 16:09:50,933] root INFO initialize: synchronously initialize the robot
[2023-06-01 16:09:59,938] root INFO Initializing TEC 0
[2023-06-01 16:10:01,940] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 16:10:03,440] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 16:10:03,440] pyhamilton.interface INFO disconnected from server
[2023-06-01 16:10:03,541] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 16:10:03,541] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 16:10:03,544] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 16:10:03,545] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 16:10:03,545] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 16:10:03,546] pyhamilton.interface INFO server thread exited
[2023-06-01 16:10:03,546] root ERROR Traceback (most recent call last):
[2023-06-01 16:10:03,546] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 21, in <module>
[2023-06-01 16:10:03,547] root ERROR initialize_tec(ham_int, 0, True)
[2023-06-01 16:10:03,548] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 13, in initialize_tec
[2023-06-01 16:10:03,548] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 16:10:03,548] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 16:10:03,548] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,549] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,550] root ERROR ^
[2023-06-01 16:10:03,551] root ERROR ^
[2023-06-01 16:10:03,551] root ERROR ^
[2023-06-01 16:10:03,551] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 16:10:03,551] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 16:10:03,551] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 16:10:03,551] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 16:10:03,551] root ERROR pyhamilton.oemerr
[2023-06-01 16:10:03,551] root ERROR .
[2023-06-01 16:10:03,552] root ERROR HamiltonStepError
[2023-06-01 16:10:03,552] root ERROR : 
[2023-06-01 16:10:03,552] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_Initialize","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af348c0529a"} )
[2023-06-01 16:22:08,195] root INFO ########################################################################
[2023-06-01 16:22:08,195] root INFO #                                                                      #
[2023-06-01 16:22:08,195] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 16:22:08,196] root INFO #                                                                      #
[2023-06-01 16:22:08,196] root INFO ########################################################################
[2023-06-01 16:22:08,196] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 16:22:08,196] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 16:22:08,196] pyhamilton.interface INFO started the server thread
[2023-06-01 16:22:08,196] root INFO initialize: synchronously initialize the robot
[2023-06-01 16:22:19,204] root INFO Initializing TEC 0
[2023-06-01 16:22:20,205] root INFO Set target temperature 0 1 to 30 degrees C
[2023-06-01 16:22:22,207] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 16:22:23,707] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 16:22:23,707] pyhamilton.interface INFO disconnected from server
[2023-06-01 16:22:23,808] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 16:22:23,808] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 16:22:23,810] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 16:22:23,810] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 16:22:23,812] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 16:22:23,812] pyhamilton.interface INFO server thread exited
[2023-06-01 16:40:57,335] root INFO ########################################################################
[2023-06-01 16:40:57,335] root INFO #                                                                      #
[2023-06-01 16:40:57,336] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 16:40:57,336] root INFO #                                                                      #
[2023-06-01 16:40:57,336] root INFO ########################################################################
[2023-06-01 16:40:57,336] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 16:40:57,336] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 16:40:57,336] pyhamilton.interface INFO started the server thread
[2023-06-01 16:40:57,336] root INFO initialize: synchronously initialize the robot
[2023-06-01 16:41:08,343] root INFO Initializing TEC 0
[2023-06-01 16:41:09,351] root INFO Set target temperature 0 1 to 30 degrees C
[2023-06-01 16:41:10,355] root INFO Starting temperature control 0 1
[2023-06-01 16:41:12,363] root INFO Ending temperature control 0 1
[2023-06-01 16:41:14,365] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 16:41:15,868] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 16:41:15,868] pyhamilton.interface INFO disconnected from server
[2023-06-01 16:41:15,969] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 16:41:15,969] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 16:41:15,975] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 16:41:15,977] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 16:41:15,978] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 16:41:15,979] pyhamilton.interface INFO server thread exited
[2023-06-01 16:41:15,979] root ERROR Traceback (most recent call last):
[2023-06-01 16:41:15,980] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 25, in <module>
[2023-06-01 16:41:15,980] root ERROR stop_control_tec(ham_int, 0, 1)
[2023-06-01 16:41:15,981] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 28, in stop_control_tec
[2023-06-01 16:41:15,981] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 16:41:15,982] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 16:41:15,982] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 16:41:15,983] root ERROR ^
[2023-06-01 16:41:15,983] root ERROR ^
[2023-06-01 16:41:15,983] root ERROR ^
[2023-06-01 16:41:15,983] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,984] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,985] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,986] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,987] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,988] root ERROR ^
[2023-06-01 16:41:15,989] root ERROR ^
[2023-06-01 16:41:15,989] root ERROR ^
[2023-06-01 16:41:15,989] root ERROR ^
[2023-06-01 16:41:15,989] root ERROR ^
[2023-06-01 16:41:15,989] root ERROR ^
[2023-06-01 16:41:15,989] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 16:41:15,990] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 16:41:15,990] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 16:41:15,991] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 16:41:15,991] root ERROR pyhamilton.oemerr
[2023-06-01 16:41:15,992] root ERROR .
[2023-06-01 16:41:15,992] root ERROR HamiltonStepError
[2023-06-01 16:41:15,992] root ERROR : 
[2023-06-01 16:41:15,992] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_StopTemperatureControl","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af3b85b4706"} )
[2023-06-01 16:45:50,200] root INFO ########################################################################
[2023-06-01 16:45:50,200] root INFO #                                                                      #
[2023-06-01 16:45:50,200] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 16:45:50,200] root INFO #                                                                      #
[2023-06-01 16:45:50,200] root INFO ########################################################################
[2023-06-01 16:45:50,201] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 16:45:50,201] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 16:45:50,201] pyhamilton.interface INFO started the server thread
[2023-06-01 16:45:50,201] root INFO initialize: synchronously initialize the robot
[2023-06-01 16:46:07,243] root INFO Initializing TEC 0
[2023-06-01 16:46:08,244] root INFO Set target temperature 0 1 to 30 degrees C
[2023-06-01 16:46:09,245] root INFO Starting temperature control 0 1
[2023-06-01 16:46:11,246] root INFO Ending temperature control 0 1
[2023-06-01 16:46:12,247] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 16:46:13,747] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 16:46:13,748] pyhamilton.interface INFO disconnected from server
[2023-06-01 16:46:13,848] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 16:46:13,848] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 16:46:13,852] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 16:46:13,854] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 16:46:13,854] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 16:46:13,854] pyhamilton.interface INFO server thread exited
[2023-06-01 16:46:13,855] root ERROR Traceback (most recent call last):
[2023-06-01 16:46:13,855] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 25, in <module>
[2023-06-01 16:46:13,856] root ERROR stop_control_tec(ham_int, 0, 1)
[2023-06-01 16:46:13,856] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 28, in stop_control_tec
[2023-06-01 16:46:13,857] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 16:46:13,857] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 16:46:13,858] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 16:46:13,858] root ERROR ^
[2023-06-01 16:46:13,858] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,859] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,860] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,861] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,862] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,864] root ERROR ^
[2023-06-01 16:46:13,865] root ERROR ^
[2023-06-01 16:46:13,865] root ERROR ^
[2023-06-01 16:46:13,865] root ERROR ^
[2023-06-01 16:46:13,865] root ERROR ^
[2023-06-01 16:46:13,865] root ERROR ^
[2023-06-01 16:46:13,865] root ERROR ^
[2023-06-01 16:46:13,866] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 16:46:13,867] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 16:46:13,868] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 16:46:13,868] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 16:46:13,869] root ERROR pyhamilton.oemerr
[2023-06-01 16:46:13,869] root ERROR .
[2023-06-01 16:46:13,869] root ERROR HamiltonStepError
[2023-06-01 16:46:13,869] root ERROR : 
[2023-06-01 16:46:13,869] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_StopTemperatureControl","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af3ca2bdc10"} )
[2023-06-01 18:16:48,522] root INFO ########################################################################
[2023-06-01 18:16:48,522] root INFO #                                                                      #
[2023-06-01 18:16:48,522] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 18:16:48,522] root INFO #                                                                      #
[2023-06-01 18:16:48,523] root INFO ########################################################################
[2023-06-01 18:16:48,523] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 18:16:48,523] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 18:16:48,523] pyhamilton.interface INFO started the server thread
[2023-06-01 18:16:48,523] root INFO initialize: synchronously initialize the robot
[2023-06-01 18:17:00,533] root INFO Initializing TEC 0
[2023-06-01 18:17:01,534] root INFO Set target temperature 0 1 to 30 degrees C
[2023-06-01 18:17:02,535] root INFO Starting temperature control 0 1
[2023-06-01 18:17:03,536] root INFO Ending temperature control 0 1
[2023-06-01 18:17:04,537] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 18:17:06,038] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 18:17:06,038] pyhamilton.interface INFO disconnected from server
[2023-06-01 18:17:06,139] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 18:17:06,139] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 18:17:06,146] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 18:17:06,147] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 18:17:06,148] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 18:17:06,148] pyhamilton.interface INFO server thread exited
[2023-06-01 18:17:06,148] root ERROR Traceback (most recent call last):
[2023-06-01 18:17:06,149] root ERROR   File "C:\Users\stefa\inheco_tec\robot_method.py", line 25, in <module>
[2023-06-01 18:17:06,149] root ERROR stop_control_tec(ham_int, 0, 1)
[2023-06-01 18:17:06,149] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\tec_wrappers.py", line 28, in stop_control_tec
[2023-06-01 18:17:06,150] root ERROR ham.wait_on_response(cid, raise_first_exception=True, timeout=120)
[2023-06-01 18:17:06,150] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 657, in wait_on_response
[2023-06-01 18:17:06,151] root ERROR return self.parse_response(server_response, raise_first_exception, return_data)
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,151] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,153] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,154] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,155] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,156] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR ^
[2023-06-01 18:17:06,157] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 676, in parse_response
[2023-06-01 18:17:06,158] root ERROR hamiltonResponse.raise_first_exception()
[2023-06-01 18:17:06,159] root ERROR   File "c:\users\stefa\pyhamilton\pyhamilton\interface.py", line 400, in raise_first_exception
[2023-06-01 18:17:06,159] root ERROR raise HamiltonStepError('Hamilton step did not execute correctly; no error code given. ( response: ' + self.raw + ' )')
[2023-06-01 18:17:06,160] root ERROR pyhamilton.oemerr
[2023-06-01 18:17:06,160] root ERROR .
[2023-06-01 18:17:06,160] root ERROR HamiltonStepError
[2023-06-01 18:17:06,160] root ERROR : 
[2023-06-01 18:17:06,160] root ERROR Hamilton step did not execute correctly; no error code given. ( response: {"command":"STAR-return","step-name":"TEC_StopTemperatureControl","step-return1":"0","step-return2":"","step-return3":"","step-return4":"","id":"0x1af50f27312f"} )
[2023-06-01 18:17:46,405] root INFO ########################################################################
[2023-06-01 18:17:46,405] root INFO #                                                                      #
[2023-06-01 18:17:46,406] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 18:17:46,406] root INFO #                                                                      #
[2023-06-01 18:17:46,406] root INFO ########################################################################
[2023-06-01 18:17:46,406] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 18:17:46,406] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 18:17:46,406] pyhamilton.interface INFO started the server thread
[2023-06-01 18:17:46,406] root INFO initialize: synchronously initialize the robot
[2023-06-01 18:17:59,416] root INFO Initializing TEC 0
[2023-06-01 18:18:00,416] root INFO Set target temperature 0 1 to 30 degrees C
[2023-06-01 18:18:01,417] root INFO Starting temperature control 0 1
[2023-06-01 18:18:02,418] root INFO Ending temperature control 0 1
[2023-06-01 18:18:03,419] root INFO Terminating TEC
[2023-06-01 18:18:04,419] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 18:18:05,921] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 18:18:05,924] pyhamilton.interface INFO disconnected from server
[2023-06-01 18:18:06,044] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 18:18:06,045] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 18:18:06,053] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 18:18:06,055] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 18:18:06,056] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 18:18:06,057] pyhamilton.interface INFO server thread exited
[2023-06-01 18:19:41,902] root INFO ########################################################################
[2023-06-01 18:19:41,903] root INFO #                                                                      #
[2023-06-01 18:19:41,903] root INFO #     Begin execution of C:\Users\stefa\inheco_tec\robot_method.py     #
[2023-06-01 18:19:41,903] root INFO #                                                                      #
[2023-06-01 18:19:41,903] root INFO ########################################################################
[2023-06-01 18:19:41,903] pyhamilton.interface INFO starting a Hamilton interface
[2023-06-01 18:19:41,903] pyhamilton.interface INFO started the oem application for simulation
[2023-06-01 18:19:41,904] pyhamilton.interface INFO started the server thread
[2023-06-01 18:19:41,904] root INFO initialize: synchronously initialize the robot
[2023-06-01 18:19:53,915] root INFO Initializing TEC 0
[2023-06-01 18:19:55,918] root INFO Set target temperature 0 1 to 30 degrees C
[2023-06-01 18:19:56,919] root INFO Starting temperature control 0 1
[2023-06-01 18:19:57,921] root INFO Ending temperature control 0 1
[2023-06-01 18:19:58,924] root INFO Terminating TEC
[2023-06-01 18:19:59,925] pyhamilton.interface INFO sending end run command to simulator
[2023-06-01 18:20:01,425] pyhamilton.interface ERROR HamiltonTimeoutError('Timed out after 1.5 sec while waiting for response id 0x0')
[2023-06-01 18:20:01,425] pyhamilton.interface INFO disconnected from server
[2023-06-01 18:20:01,526] pyhamilton.interface INFO server did not exit yet, sending dummy request to exit its loop
[2023-06-01 18:20:01,526] urllib3.util.retry DEBUG Converted retries value: 20 -> Retry(total=20, connect=None, read=None, redirect=None, status=None)
[2023-06-01 18:20:01,530] urllib3.connectionpool DEBUG Starting new HTTP connection (1): 127.0.0.1:3221
[2023-06-01 18:20:01,531] urllib3.connectionpool DEBUG http://127.0.0.1:3221 "GET / HTTP/1.1" 200 None
[2023-06-01 18:20:01,533] pyhamilton.interface INFO dummy get request sent to server
[2023-06-01 18:20:01,533] pyhamilton.interface INFO server thread exited
